export default [
  {
    ignores: ["frontend/vendor/**", "portable/**", "node_modules/**", "mac_analyzer_standalone.html"],
  },
  {
    files: ["app.js", "frontend/*.js", "tests/*.test.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: Object.fromEntries([
        "AbortController", "Blob", "Buffer", "Chart", "CustomEvent", "DOMParser",
        "DecompressionStream", "File", "IDBKeyRange", "MutationObserver",
        "Response", "TextDecoder", "TextEncoder", "URL", "URLSearchParams",
        "__dirname", "atob", "btoa", "cancelAnimationFrame", "clearInterval",
        "clearTimeout", "confirm", "console", "crypto", "document", "fetch",
        "getComputedStyle", "global", "history", "indexedDB", "localStorage",
        "location", "module", "navigator", "performance", "process",
        "queueMicrotask", "requestAnimationFrame", "require", "self",
        "sessionStorage", "setInterval", "setTimeout", "window", "Worker",
      ].map((name) => [name, "readonly"])),
    },
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-const-assign": "error",
      "no-control-regex": "off",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-new-native-nonconstructor": "error",
      "no-obj-calls": "error",
      "no-promise-executor-return": "off",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-unexpected-multiline": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-with": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error"
    }
  }
];
